routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\DoctorController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});

Route::get('/test', function () {
    return view('test');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin']], function() {
    Route::resource('doctor', DoctorController::class);
});

Route::group(['middleware' => ['auth', 'doctor']], function() {
    Route::resource('appointment', AppointmentController::class);
    Route::post('appointment/check', 'AppointmentController@check')->name('appointment.check');
    Route::post('appointment/update', 'AppointmentController@updateTime')->name('appointment.update');
});

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\User;
use Illuminate\Http\Request;

class DoctorController extends Controller
{
    public function index()
    {
        $doctors = User::where('role_id', 1)->get();
        return view('admin.doctor.index', compact('doctors'));
    }

    public function create()
    {
        $roles = Role::where('name', '!=', 'patient')->get();

        return view('admin.doctor.create', compact('roles'));
    }

    public function store(Request $request)
    {
        $this->validateData();
        $data = $request->input();

        $name = (new User)->userAvatar();

        $data['image'] = $name;
        $data['password'] = bcrypt($request->password);
        User::create($data);

        return redirect()->route('doctor.index')->with('message', 'Doctor added successfully');
    }

    public function show(User $doctor)
    {
        return view('admin.doctor.delete', compact('doctor'));
    }

    public function edit(User $doctor)
    {
        $roles = Role::where('name', '!=', 'patient')->get();
        return view('admin.doctor.edit', compact('doctor', 'roles'));
    }

    public function update(Request $request, User $doctor)
    {
        $this->validateUpdate($doctor->id);
        $data = $request->input();
        $imageName = $doctor->image;
        $doctorPassword = $doctor->password;
        if($request->hasFile('image')) {
            $imageName = (new User)->userAvatar();
            unlink(public_path('images/' . $doctor->image));
        }
        $data['image'] = $imageName;
        if($request->password) {
            $data['password'] = bcrypt($request->password);
        }else {
            $data['password'] = $doctorPassword;
        }

        $doctor->update($data);

        return redirect()->route('doctor.index')->with('message', 'Doctor updated successfully');
    }

    public function destroy(User $doctor)
    {
        if(auth()->id() == $doctor->id) {
            abort(401);
        }
        $doctorDelete = $doctor->delete();
        if($doctorDelete) {
            unlink(public_path('images/' . $doctor->image));
        }

        return redirect()->route('doctor.index')->with('message', 'Doctor deleted successfully');
    }

    public function validateData()
    {
        return request()->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6|max:25',
            'gender' => 'required',
            'education' => 'required',
            'address' => 'required',
            'department' => 'required',
            'phone_number' => 'required|numeric',
            'image' => 'required|mimes:jpeg,jpg,png,svg',
            'role_id' => 'required',
            'description' => 'required',
        ]);
    }

    public function validateUpdate($id)
    {
        return request()->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'nullable|min:6|max:25',
            'gender' => 'required',
            'education' => 'required',
            'address' => 'required',
            'department' => 'required',
            'phone_number' => 'required|numeric',
            'image' => 'nullable|mimes:jpeg,jpg,png,svg',
            'role_id' => 'required',
            'description' => 'required',
        ]);
    }
}

resources/views/admin/doctor/create.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="page-header">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="ik ik-edit bg-blue"></i>
                    <div class="d-inline">
                        <h5>Doctors</h5>
                        <span>Add Doctor</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <nav class="breadcrumb-container" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="../index.html"><i class="ik ik-home"></i></a>
                        </li>
                        <li class="breadcrumb-item"><a href="{{ route('doctor.index') }}">Doctor</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-10">

            <div class="card">
                <div class="card-header">
                    <h3>Add Doctor</h3>
                </div>
                <div class="card-body">
                    <form action="{{ route('doctor.store') }}" method="POST" class="forms-sample" enctype="multipart/form-data" autocomplete="off">
                        @csrf
                        <div class="row">
                            <div class="col-lg-6">
                                <label for="name">Full Name</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name" placeholder="Enter Name" value="{{ old('name') }}">
                                @error('name') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                            <div class="col-lg-6">
                                <label for="email">Email</label>
                                <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" id="email" placeholder="Enter Email" value="{{ old('email') }}">
                                @error('email') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <label for="password">Password</label>
                                <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" id="password" placeholder="Enter Password">
                                @error('password') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                            <div class="col-lg-6">
                                <label for="gender">Gender</label>
                                <select name="gender" id="gender" class="form-control @error('gender') is-invalid @enderror">
                                    <option value=""></option>
                                    <option value="male">Male</option>
                                    <option value="female">Female</option>
                                </select>
                                @error('gender') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <label for="education">Education</label>
                                <input type="text" class="form-control @error('education') is-invalid @enderror" name="education" id="education" placeholder="Enter Doctor Highest Degree" value="{{ old('education') }}">
                                @error('education') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                            <div class="col-lg-6">
                                <label for="address">Address</label>
                                <input type="text" class="form-control @error('address') is-invalid @enderror" name="address" id="address" placeholder="Enter Address" value="{{ old('address') }}">
                                @error('address') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <label for="department">Specialist</label>
{{--                                <input type="text" class="form-control @error('department') is-invalid @enderror" name="department" id="department" value="{{ old('department') }}">--}}
                                <select name="department" id="department" class="form-control @error('department') is-invalid @enderror">
                                    @foreach(['Cardiologist', 'Family-Physician', 'Ophthalmologist', 'Neurologist', 'Dentist'] as $department)
                                        <option value="{{ $department }}" @if(old('department') == $department) selected @endif>{{ $department }}</option>
                                    @endforeach
                                </select>
                                @error('department') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                            <div class="col-lg-6">
                                <label for="phone_number">Phone Number</label>
                                <input type="text" class="form-control @error('phone_number') is-invalid @enderror" name="phone_number" id="phone_number" placeholder="Enter Phone Number" value="{{ old('phone_number') }}">
                                @error('phone_number') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Image</label>
                                    <input type="file" class="form-control file-upload-info @error('image') is-invalid @enderror" name="image" placeholder="Upload Image">
                                    <span class="input-group-append">
                                    </span>
                                    @error('image') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Role</label>
                                <select name="role_id" id="role_id" class="form-control @error('role_id') is-invalid @enderror">
                                    <option selected disabled>Select Role</option>
                                    @foreach($roles as $role)
                                        <option value="{{ $role->id }}">{{ $role->name }}</option>
                                    @endforeach
                                </select>
                                @error('role_id') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea name="description" id="description" rows="4" class="form-control @error('description') is-invalid @enderror">{{ old('description') }}</textarea>
                            @error('description') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                        </div>
                        <button class="btn btn-primary mr-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/doctor/delete.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="page-header">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="ik ik-edit bg-blue"></i>
                    <div class="d-inline">
                        <h5>Doctors</h5>
                        <span>Delete Doctor</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <nav class="breadcrumb-container" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="../index.html"><i class="ik ik-home"></i></a>
                        </li>
                        <li class="breadcrumb-item"><a href="{{ route('doctor.index') }}">Doctor</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Delete</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-10">

            <div class="card">
                <div class="card-header">
                    <h3>Confirm Deletion</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <img src="{{ asset('images') }}/{{ $doctor->image }}" width="120" style="border-radius: 50%;">
                        <h2 class="ml-4">{{ $doctor->name }}</h2>
                    </div>
                    <form action="{{ route('doctor.destroy', $doctor->id) }}" method="POST" class="forms-sample" autocomplete="off">
                        @csrf
                        @method('DELETE')
                        <div class="card-footer">
                            <button class="btn btn-danger mr-2">Confirm</button>
                            <a href="{{ route('doctor.index') }}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/doctor/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="page-header">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="ik ik-edit bg-blue"></i>
                    <div class="d-inline">
                        <h5>Doctors</h5>
                        <span>Edit Doctor</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <nav class="breadcrumb-container" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="../index.html"><i class="ik ik-home"></i></a>
                        </li>
                        <li class="breadcrumb-item"><a href="{{ route('doctor.index') }}">Doctor</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Edit</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-10">
            @if(Session::has('message'))
                <div class="alert alert-success">{{ Session::get('message') }}</div>
            @endif
            <div class="card">
                <div class="card-header">
                    <h3>Edit Doctor</h3>
                </div>
                <div class="card-body">
                    <form action="{{ route('doctor.update', [$doctor->id]) }}" method="POST" class="forms-sample" enctype="multipart/form-data" autocomplete="off">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-lg-6">
                                <label for="name">Full Name</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name" placeholder="Enter Name" value="{{ $doctor->name ?? old('name') }}">
                                @error('name') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                            <div class="col-lg-6">
                                <label for="email">Email</label>
                                <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" id="email" placeholder="Enter Email" value="{{ $doctor->email ?? old('email') }}">
                                @error('email') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <label for="password">Password</label>
                                <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" id="password" placeholder="Enter Password">
                                @error('password') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                            <div class="col-lg-6">
                                <label for="gender">Gender</label>
                                <select name="gender" id="gender" class="form-control @error('gender') is-invalid @enderror">
                                    <option value=""></option>
                                    <option value="male" @if($doctor->gender == 'male') selected @endif>Male</option>
                                    <option value="female" @if($doctor->gender == 'female') selected @endif>Female</option>
                                </select>
                                @error('gender') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <label for="education">Education</label>
                                <input type="text" class="form-control @error('education') is-invalid @enderror" name="education" id="education" placeholder="Enter Doctor Highest Degree" value="{{ $doctor->education ?? old('education') }}">
                                @error('education') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                            <div class="col-lg-6">
                                <label for="address">Address</label>
                                <input type="text" class="form-control @error('address') is-invalid @enderror" name="address" id="address" placeholder="Enter Address" value="{{ $doctor->address ?? old('address') }}">
                                @error('address') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <label for="department">Specialist</label>
                                <select name="department" id="department" class="form-control @error('department') is-invalid @enderror">
                                    @foreach(['Cardiologist', 'Family-Physician', 'Ophthalmologist', 'Neurologist', 'Dentist'] as $department)
                                        <option value="{{ $department }}" @if($doctor->department == $department) selected @endif>{{ $department }}</option>
                                    @endforeach
                                </select>
{{--                                <input type="text" class="form-control @error('department') is-invalid @enderror" name="department" id="department" value="{{ $doctor->department ?? old('department') }}">--}}
                                @error('department') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                            <div class="col-lg-6">
                                <label for="phone_number">Phone Number</label>
                                <input type="text" class="form-control @error('phone_number') is-invalid @enderror" name="phone_number" id="phone_number" placeholder="Enter Phone Number" value="{{ $doctor->phone_number ?? old('phone_number') }}">
                                @error('phone_number') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Image</label>
                                    <input type="file" class="form-control file-upload-info @error('image') is-invalid @enderror" name="image" placeholder="Upload Image">
                                    <span class="input-group-append">
                                    </span>
                                    @error('image') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Role</label>
                                <select name="role_id" id="role_id" class="form-control @error('role_id') is-invalid @enderror">
                                    <option selected disabled>Select Role</option>
                                    @foreach($roles as $role)
                                        <option value="{{ $role->id }}" @if($doctor->role_id == $role->id) selected @endif>{{ $role->name }}</option>
                                    @endforeach
                                </select>
                                @error('role_id') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea name="description" id="description" rows="4" class="form-control @error('description') is-invalid @enderror">{{ $doctor->description ?? old('description') }}</textarea>
                            @error('description') <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span> @enderror
                        </div>
                        <button class="btn btn-primary mr-2">Update</button>
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/doctor/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="page-header">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="ik ik-inbox bg-blue"></i>
                    <div class="d-inline">
                        <h5>Doctors</h5>
                        <span>List Of All Doctors</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <nav class="breadcrumb-container" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="../index.html"><i class="ik ik-home"></i></a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Doctors</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            @if(Session::has('message'))
                <div class="alert alert-success">{{ Session::get('message') }}</div>
            @endif
            <div class="card">
                <div class="card-header"><h3>Data Table</h3></div>
                <div class="card-body">
                    <table id="data_table" class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th class="nosort">Avatar</th>
                            <th>Email</th>
                            <th>Address</th>
                            <th>Phone Number</th>
                            <th>Department</th>
                            <th class="nosort">&nbsp;</th>
                            <th class="nosort">&nbsp;</th>
                        </tr>
                        </thead>
                        <tbody>
                            @forelse($doctors as $doctor)
                                <tr>
                                    <td>{{ $doctor->name }}</td>
                                    <td><img src="{{ asset('/images/' . $doctor->image) }}" class="table-user-thumb" alt=""></td>
                                    <td>{{ $doctor->email }}</td>
                                    <td>{{ $doctor->address }}</td>
                                    <td>{{ $doctor->phone_number }}</td>
                                    <td>{{ $doctor->department }}</td>
                                    <td>
                                        <div class="table-actions">
                                            <a href="#" data-toggle="modal" data-target="#exampleModal{{ $doctor->id }}"><i class="ik ik-eye text-blue"></i></a>
                                            <a href="{{ route('doctor.edit', $doctor->id) }}"><i class="ik ik-edit-2 text-success"></i></a>
                                            <a href="{{ route('doctor.show', $doctor->id) }}"><i class="ik ik-trash-2 text-danger"></i></a>
                                        </div>
                                    </td>
                                    <td></td>
                                </tr>
                                @include('admin.doctor.modal')
                            @empty
                                <td>No doctors to display</td>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/doctor/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModal{{$doctor->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Doctor Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p><img src="{{ asset('/images') }}/{{ $doctor->image }}" width="200"></p>
                <p class="badge badge-pill badge-dark">Role: {{ $doctor->role->name }}</p>
                <p><strong>Name: </strong>{{ $doctor->name }}</p>
                <p><strong>Email: </strong>{{ $doctor->email }}</p>
                <p><strong>Address: </strong>{{ $doctor->address }}</p>
                <p><strong>Phone Number: </strong>{{ $doctor->phone_number }}</p>
                <p><strong>Department: </strong>{{ $doctor->department }}</p>
                <p><strong>Education: </strong>{{ $doctor->education }}</p>
                <p><strong>Bio: </strong>{{ $doctor->description }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>